// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMQC04btRNAvwchooOAsLsibos7vPPTa8',
    appId: '1:881846428253:web:00d88c9ade03d163d723b4',
    messagingSenderId: '881846428253',
    projectId: 'pocketwise-a0fe0',
    authDomain: 'pocketwise-a0fe0.firebaseapp.com',
    storageBucket: 'pocketwise-a0fe0.firebasestorage.app',
    measurementId: 'G-08YL3L0Y5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6XHtpVqSjv4rJMG4Rs3EWU6RZf7x6nE8',
    appId: '1:881846428253:android:84edf48d656594fbd723b4',
    messagingSenderId: '881846428253',
    projectId: 'pocketwise-a0fe0',
    storageBucket: 'pocketwise-a0fe0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALVvrHnBLHd_WGYMnS2yLCx9sicuUsHWU',
    appId: '1:881846428253:ios:82d58bc305285e19d723b4',
    messagingSenderId: '881846428253',
    projectId: 'pocketwise-a0fe0',
    storageBucket: 'pocketwise-a0fe0.firebasestorage.app',
    iosBundleId: 'com.example.pocketwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALVvrHnBLHd_WGYMnS2yLCx9sicuUsHWU',
    appId: '1:881846428253:ios:82d58bc305285e19d723b4',
    messagingSenderId: '881846428253',
    projectId: 'pocketwise-a0fe0',
    storageBucket: 'pocketwise-a0fe0.firebasestorage.app',
    iosBundleId: 'com.example.pocketwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMQC04btRNAvwchooOAsLsibos7vPPTa8',
    appId: '1:881846428253:web:34ae5da6202e9dcad723b4',
    messagingSenderId: '881846428253',
    projectId: 'pocketwise-a0fe0',
    authDomain: 'pocketwise-a0fe0.firebaseapp.com',
    storageBucket: 'pocketwise-a0fe0.firebasestorage.app',
    measurementId: 'G-L37X4RZVV6',
  );
}
